### PR TITLE
Atualizacao da secao welcome

### PR DESCRIPTION
**Pull request by leviferreira**
Galera, por favor validar se essa tradução está correta. O texto traduzido foi:

> There’s a lot of outdated information on the Web that leads new PHP users astray, propagating bad practices and insecure code. PHP: The Right Way is an easy-to-read, quick reference for PHP popular coding standards, links to authoritative tutorials around the Web and what the contributors consider to be best practices at the present time.
> 
> There is no canonical way to use PHP. This website aims to introduce new PHP developers to some topics which they may not discover until it is too late, and aims to give seasoned pros some fresh ideas on those topics they’ve been doing for years without ever reconsidering. This website will also not tell you which tools to use, but instead offer suggestions for multiple options, when possible explaining the differences in approach and use-case.
> 
> This is a living document and will continue to be updated with more helpful information and examples as they become available.

Feito com base no projeto codeguy/php-the-right-way commit 72e5a6b99cb177b1fcf1f916758ec768d2c45f1c

### CODE REVIEW

**Comment by rogeriopradoj** [comment]
Levi, build quebrado, não vamos aceitar por enquanto.

Se você quiser, mantemos esse PR aberto, dessa forma você pode consertar e nos avisar quando estiver pronto.

**Comment by rogeriopradoj** [comment]
@leviferreira, fazer verificar.

**Comment by leviferreira** [comment]
@rogeriopradoj por favor, validar agora se a build está passando.

[]s

**Comment by rogeriopradoj** [comment]
Valeu @leviferreira

**Pull request merged**
